# Site settings
title: _nikolas
author: Nikolas Silva
email: nikolas.rsilva@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site de testes para pequenos projetos front-end.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://n19.github.io" # the base hostname & protocol for your site
github_username:  N19

# Build settings
markdown: kramdown

links:
  - title: home
    url: /
  - title: sobre
    url: /sobre
  - title: contato
    url: /contato
